SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BOX;
DROP TABLE IF EXISTS CELL;
DROP TABLE IF EXISTS CABINET;
DROP TABLE IF EXISTS RACK;
DROP TABLE IF EXISTS ROOM;




/* Create Tables */

CREATE TABLE BOX
(
	BOX_ID varchar(32) NOT NULL,
	_NUMBER varchar(32) NOT NULL,
	_FULL boolean NOT NULL,
	EMPTY boolean NOT NULL,
	_SIZE int NOT NULL,
	SEQ int NOT NULL,
	DESCRIPTION varchar(256),
	CELL_ID varchar(24) NOT NULL,
	PRIMARY KEY (BOX_ID),
	UNIQUE (_NUMBER)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CABINET
(
	CABINET_ID varchar(16) NOT NULL,
	NAME varchar(8) NOT NULL,
	RACK_ID varchar(8) NOT NULL,
	SEQ int NOT NULL,
	PRIMARY KEY (CABINET_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CELL
(
	CELL_ID varchar(24) NOT NULL,
	NAME varchar(8) NOT NULL,
	CABINET_ID varchar(16) NOT NULL,
	_SIZE int,
	_FULL boolean NOT NULL,
	SEQ int NOT NULL,
	PRIMARY KEY (CELL_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RACK
(
	RACK_ID varchar(8) NOT NULL,
	NAME varchar(4) NOT NULL,
	ROOM_ID varchar(4) NOT NULL,
	PRIMARY KEY (RACK_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE ROOM
(
	ROOM_ID varchar(4) NOT NULL,
	NAME varchar(16) NOT NULL,
	DESCRIPTION varchar(256),
	PRIMARY KEY (ROOM_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE CELL
	ADD FOREIGN KEY (CABINET_ID)
	REFERENCES CABINET (CABINET_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOX
	ADD FOREIGN KEY (CELL_ID)
	REFERENCES CELL (CELL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CABINET
	ADD FOREIGN KEY (RACK_ID)
	REFERENCES RACK (RACK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RACK
	ADD FOREIGN KEY (ROOM_ID)
	REFERENCES ROOM (ROOM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



