SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BUSINESS_FIELD;
DROP TABLE IF EXISTS VOL_CONETXT;
DROP TABLE IF EXISTS VOLUME;
DROP TABLE IF EXISTS RECORD_BUSINESS;




/* Create Tables */

CREATE TABLE BUSINESS_FIELD
(
  FIELD_ID varchar(32) NOT NULL,
  BUSINESS_ID varchar(32) NOT NULL,
  NAME varchar(16) NOT NULL,
  _VALUE text,
  ORDINAL int NOT NULL,
  TYPE varchar(32) NOT NULL,
  DISPLAY_OPTION text,
  SUMMARY varchar(256),
  PRIMARY KEY (FIELD_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RECORD_BUSINESS
(
  BUSINESS_ID varchar(32) NOT NULL,
  DEFINE_ID varchar(32),
  DEFINE_NAME varchar(16) NOT NULL,
  DELIVER varchar(32) NOT NULL,
  DELIVER_ID varchar(32) NOT NULL,
  RECEIVE_DATE date NOT NULL,
  MEMO varchar(256),
  _KEY varchar(512),
  STATUS varchar(8) NOT NULL,
  _VERSION int NOT NULL,
  SUMMARY text NOT NULL,
  _SOURCE varchar(8) NOT NULL,
  PRIMARY KEY (BUSINESS_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE VOLUME
(
  VOLUME_ID varchar(64) NOT NULL,
  BUSINESS_ID varchar(32) NOT NULL,
  BOX_ID varchar(32) NOT NULL,
  PAGE_COUNT int,
  SECRECY_LEVEL varchar(8) NOT NULL,
  ORDINAL int NOT NULL,
  RECORD_TIME date NOT NULL,
  PRIMARY KEY (VOLUME_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE VOL_CONETXT
(
  CONTEXT_ID varchar(32) NOT NULL,
  BUSINESS_ID varchar(32) NOT NULL,
  TYPE varchar(8) NOT NULL,
  ORDINAL int NOT NULL,
  PAGE_BEGIN int NOT NULL,
  PAGE_END int NOT NULL,
  NAME varchar(32) NOT NULL,
  PRIMARY KEY (CONTEXT_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE BUSINESS_FIELD
  ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES RECORD_BUSINESS (BUSINESS_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


ALTER TABLE VOL_CONETXT
  ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES RECORD_BUSINESS (BUSINESS_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


ALTER TABLE VOLUME
  ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES RECORD_BUSINESS (BUSINESS_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;

