SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS FIELD_VALUE;
DROP TABLE IF EXISTS BUSINESS_FIELD_GROUP;
DROP TABLE IF EXISTS VOL_CONETXT;
DROP TABLE IF EXISTS VOLUME;
DROP TABLE IF EXISTS RECORD_BUSINESS;




/* Create Tables */

CREATE TABLE BUSINESS_FIELD_GROUP
(
  FIELD_ID varchar(32) NOT NULL,
  BUSINESS_ID varchar(32) NOT NULL,
  NAME varchar(16) NOT NULL,
  TYPE varchar(32) NOT NULL,
  _ORDINAL int NOT NULL,
  _OPTION text,
  _ROW int NOT NULL,
  DEFINE varchar(32),
  PRIMARY KEY (FIELD_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIELD_VALUE
(
  VALUE_ID bigint NOT NULL AUTO_INCREMENT,
  _PATTERN varchar(32),
  _VALUE text,
  FIELD_ID varchar(32) NOT NULL,
  _ORDINAL int NOT NULL,
  LABEL varchar(32),
  _OPTION text,
  PRIMARY KEY (VALUE_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RECORD_BUSINESS
(
  BUSINESS_ID varchar(32) NOT NULL,
  DEFINE_ID varchar(32),
  DEFINE_NAME varchar(16) NOT NULL,
  DEFINE_VER int NOT NULL,
  DELIVER_TYPE varchar(16) NOT NULL,
  DELIVER varchar(32) NOT NULL,
  DELIVER_ID varchar(32) NOT NULL,
  RECEIVE_DATE date NOT NULL,
  MEMO varchar(256),
  _KEY varchar(512),
  STATUS varchar(8) NOT NULL,
  _VERSION int NOT NULL,
  SUMMARY text NOT NULL,
  _SOURCE varchar(8) NOT NULL,
  SEQ bigint NOT NULL,
  PRIMARY KEY (BUSINESS_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE VOLUME
(
  VOLUME_ID varchar(64) NOT NULL,
  BUSINESS_ID varchar(32) NOT NULL,
  BOX_ID varchar(32) NOT NULL,
  PAGE_COUNT int,
  SECRECY_LEVEL varchar(8) NOT NULL,
  ORDINAL int NOT NULL,
  RECORD_TIME date NOT NULL,
  PRIMARY KEY (VOLUME_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE VOL_CONETXT
(
  CONTEXT_ID varchar(32) NOT NULL,
  BUSINESS_ID varchar(32) NOT NULL,
  TYPE varchar(8) NOT NULL,
  ORDINAL int NOT NULL,
  PAGE_BEGIN int NOT NULL,
  PAGE_END int NOT NULL,
  NAME varchar(32) NOT NULL,
  PRIMARY KEY (CONTEXT_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE FIELD_VALUE
  ADD FOREIGN KEY (FIELD_ID)
REFERENCES BUSINESS_FIELD_GROUP (FIELD_ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_FIELD_GROUP
  ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES RECORD_BUSINESS (BUSINESS_ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


ALTER TABLE VOL_CONETXT
  ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES RECORD_BUSINESS (BUSINESS_ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


ALTER TABLE VOLUME
  ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES RECORD_BUSINESS (BUSINESS_ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;



