
/* Drop Tables */

DROP TABLE IF EXISTS TASK_ACTION;
DROP TABLE IF EXISTS FIELD_DEFINE;
DROP TABLE IF EXISTS CREATE_ROLE;
DROP TABLE IF EXISTS BUSINESS_DEFINE;
DROP TABLE IF EXISTS BUSINESS_CATEGORY;




/* Create Tables */

CREATE TABLE BUSINESS_CATEGORY
(
  CATEGORY_ID varchar(32) NOT NULL,
  NAME varchar(50) NOT NULL,
  PRIORITY int NOT NULL,
  PRIMARY KEY (CATEGORY_ID)
) WITHOUT OIDS;


CREATE TABLE BUSINESS_DEFINE
(
  DEFINE_ID varchar(32) NOT NULL,
  NAME varchar(64) NOT NULL,
  WF_NAME varchar(32),
  START_PAGE varchar(256),
  CATEGORY_ID varchar(32) NOT NULL,
  MEMO varchar(512),
  -- 乐观锁
  _VERSION int,
  ROLE_PREFIX varchar(16),
  -- 动态
  DESCRIPTION varchar(512),
  PRIORITY int NOT NULL,
  ENABLE boolean NOT NULL,
  WF_VER int NOT NULL,
  CREATE_TITLE varchar(8),
  CREATE_COMPLETE_PAGE varchar(256),
  DEFAULT_ROOM varchar(4),
  DEFAULT_RACK varchar(8),
  CONSTRAINT PK_DGBIZ PRIMARY KEY (DEFINE_ID)
) WITHOUT OIDS;


CREATE TABLE CREATE_ROLE
(
  ROLE varchar(32) NOT NULL,
  DEFINE_ID varchar(32) NOT NULL,
  ID serial NOT NULL,
  PRIMARY KEY (ID)
) WITHOUT OIDS;


ALTER SEQUENCE CREATE_ROLE_ID_SEQ INCREMENT 1 RESTART 1 CACHE 1;


CREATE TABLE FIELD_DEFINE
(
  FIELD_ID varchar(32) NOT NULL,
  NAME varchar(16) NOT NULL,
  TYPE varchar(8) NOT NULL,
  _NULLABLE boolean NOT NULL,
  SEARCH_KEY boolean NOT NULL,
  MAX_VALUE int,
  MIN_VALUE int,
  ORDINAL int NOT NULL,
  _STYLE varchar(128) NOT NULL,
  DEFINE_ID varchar(32) NOT NULL,
  _ROW int NOT NULL,
  _GROUP varchar(8),
  PRIMARY KEY (FIELD_ID)
) WITHOUT OIDS;


CREATE TABLE TASK_ACTION
(
  DEFINE_ID varchar(32) NOT NULL,
  TASK_NAME varchar(128),
  TYPE varchar(8) NOT NULL,
  REG_NAME varchar(32) NOT NULL,
  PRIORITY int NOT NULL,
  ACTION_ID bigint NOT NULL,
  _POSITION varchar(8) NOT NULL,
  PRIMARY KEY (ACTION_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE BUSINESS_DEFINE
  ADD FOREIGN KEY (CATEGORY_ID)
REFERENCES BUSINESS_CATEGORY (CATEGORY_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


ALTER TABLE TASK_ACTION
  ADD FOREIGN KEY (DEFINE_ID)
REFERENCES BUSINESS_DEFINE (DEFINE_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


ALTER TABLE FIELD_DEFINE
  ADD FOREIGN KEY (DEFINE_ID)
REFERENCES BUSINESS_DEFINE (DEFINE_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


ALTER TABLE CREATE_ROLE
  ADD FOREIGN KEY (DEFINE_ID)
REFERENCES BUSINESS_DEFINE (DEFINE_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


-- test data
INSERT INTO BUSINESS_CATEGORY(CATEGORY_ID, NAME, PRIORITY) VALUES ('I','测试业务',1);
INSERT INTO BUSINESS_DEFINE(DEFINE_ID, NAME, CATEGORY_ID, _VERSION, PRIORITY, ENABLE, WF_VER)
  VALUES('I1','测试业务1','I',1,1,true,1);
INSERT INTO BUSINESS_DEFINE(DEFINE_ID, NAME, CATEGORY_ID, _VERSION, PRIORITY, ENABLE, WF_VER)
  VALUES('I2','测试业务2','I',1,1,true,1);
INSERT INTO CREATE_ROLE(ROLE, DEFINE_ID) VALUES ('USER','I1');
INSERT INTO CREATE_ROLE(ROLE, DEFINE_ID) VALUES ('USER','I2');