SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CONSTRUCT_CORP;
DROP TABLE IF EXISTS RIGHT_PROJECT_JOIN_TYPE;
DROP TABLE IF EXISTS RIGHT_CORP_TYPE;
DROP TABLE IF EXISTS PERSON_RIGHT;
DROP TABLE IF EXISTS CORP;
DROP TABLE IF EXISTS PERSON;




/* Create Tables */

CREATE TABLE CONSTRUCT_CORP
(
    REG_ID varchar(32) NOT NULL,
    CORP_TYPE varchar(16) NOT NULL,
    REG_DATE date NOT NULL,
    REG_DATE_TO date,
    _LEVEL varchar(8),
    LEVEL_NUMBER varchar(32),
    STATUS varchar(16) NOT NULL,
    CORP_ID varchar(32) NOT NULL,
    PRIMARY KEY (REG_ID),
    CONSTRAINT CORP_TYPE_UNIQUE UNIQUE (CORP_TYPE, CORP_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CORP
(
    CORP_ID varchar(32) NOT NULL,
    NAME varchar(128) NOT NULL,
    REG_ID_TYPE varchar(16) NOT NULL,
    REG_ID_NUMBER varchar(32) NOT NULL,
    OWNER_NAME varchar(64) NOT NULL,
    OWNER_ID_TYPE varchar(16) NOT NULL,
    OWNER_ID_NUMBER varchar(32) NOT NULL,
    ADDRESS varchar(256),
    TEL varchar(16),
    _VERSION bigint NOT NULL,
    DESCRIPTION varchar(256),
    ENABLE boolean NOT NULL,
    DATA_TIME datetime NOT NULL,
    PRIMARY KEY (CORP_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PERSON
(
    PERSON_ID varchar(32) NOT NULL,
    NAME varchar(64) NOT NULL,
    IDENTIFY_TYPE varchar(16) NOT NULL,
    IDENTIFY_NUMBER varchar(32) NOT NULL,
    TEL varchar(16),
    SEX varchar(6),
    BIRTH_DATE date,
    NATION varchar(16),
    NATIONALITY varchar(16),
    ADDRESS varchar(256),
    REG_ADDRESS varchar(16),
    TITLE varchar(8),
    PRIMARY KEY (PERSON_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PERSON_RIGHT
(
    RIGHT_ID varchar(32) NOT NULL,
    NAME varchar(32) NOT NULL,
    ENABLE boolean NOT NULL,
    PRI int NOT NULL,
    CORP_ID varchar(32) NOT NULL,
    STATUS varchar(16) NOT NULL,
    PERSON_ID varchar(32) NOT NULL,
    _VERSION bigint NOT NULL,
    _LEVEL varchar(8) NOT NULL,
    PRIMARY KEY (RIGHT_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RIGHT_CORP_TYPE
(
    CORP_TYPE varchar(16) NOT NULL,
    TYPE varchar(32) NOT NULL,
    PRIMARY KEY (CORP_TYPE, TYPE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RIGHT_PROJECT_JOIN_TYPE
(
    JOIN_TYPE varchar(16) NOT NULL,
    CORP_TYPE varchar(32) NOT NULL,
    PRIMARY KEY (JOIN_TYPE, CORP_TYPE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE PERSON_RIGHT
    ADD FOREIGN KEY (CORP_ID)
        REFERENCES CORP (CORP_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_CORP
    ADD FOREIGN KEY (CORP_ID)
        REFERENCES CORP (CORP_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PERSON_RIGHT
    ADD FOREIGN KEY (PERSON_ID)
        REFERENCES PERSON (PERSON_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE RIGHT_PROJECT_JOIN_TYPE
    ADD FOREIGN KEY (CORP_TYPE)
        REFERENCES PERSON_RIGHT (RIGHT_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE RIGHT_CORP_TYPE
    ADD FOREIGN KEY (TYPE)
        REFERENCES PERSON_RIGHT (RIGHT_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;





INSERT INTO CORP(CORP_ID, NAME, REG_ID_TYPE, REG_ID_NUMBER, OWNER_NAME, OWNER_ID_TYPE, OWNER_ID_NUMBER, ADDRESS, TEL, _VERSION, ENABLE, DATA_TIME)
  VALUES ('C1','测试建设单位1','OTHER','000','法人','OTHER','0001','地址','010',1,true, NOW());

INSERT INTO CONSTRUCT_CORP(REG_ID, CORP_TYPE, REG_DATE, STATUS, CORP_ID)
  VALUES('A1','CONSTRUCTION','2019-1-1' , 'NO','C1' );

INSERT INTO CORP(CORP_ID, NAME, REG_ID_TYPE, REG_ID_NUMBER, OWNER_NAME, OWNER_ID_TYPE, OWNER_ID_NUMBER, ADDRESS, TEL, _VERSION, ENABLE, DATA_TIME)
VALUES ('C3','测试建设单位2','OTHER','000','法人','OTHER','0001','地址','010',1,true, NOW());

INSERT INTO CONSTRUCT_CORP(REG_ID, CORP_TYPE, REG_DATE, STATUS, CORP_ID)
VALUES('A3','CONSTRUCTION','2019-1-1' , 'NO','C3' );

INSERT INTO CORP(CORP_ID, NAME, REG_ID_TYPE, REG_ID_NUMBER, OWNER_NAME, OWNER_ID_TYPE, OWNER_ID_NUMBER, ADDRESS, TEL, _VERSION, ENABLE, DATA_TIME)
VALUES ('C4','测试建设单位3','OTHER','000','法人','OTHER','0001','地址','010',1,true, NOW());

INSERT INTO CONSTRUCT_CORP(REG_ID, CORP_TYPE, REG_DATE, STATUS, CORP_ID)
VALUES('A4','CONSTRUCTION','2019-1-1' , 'NO','C4' );

INSERT INTO CORP(CORP_ID, NAME, REG_ID_TYPE, REG_ID_NUMBER, OWNER_NAME, OWNER_ID_TYPE, OWNER_ID_NUMBER, ADDRESS, TEL, _VERSION, ENABLE, DATA_TIME)
VALUES ('C2','测试施工单位','OTHER','000','法人','OTHER','0001','地址','010',1,true, NOW());

INSERT INTO CONSTRUCT_CORP(REG_ID, CORP_TYPE, REG_DATE, STATUS, CORP_ID)
VALUES('A2','BUILD','2019-1-1' , 'NO','C2' );


